name: CI/CD

on:
  push:
    branches:
      - main
      - feature/github_actions

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Install dependencies on Linux
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y libboost-test-dev

      - name: Install dependencies on macOS
        if: ${{ runner.os == 'macOS' }}
        run: |
          brew update
          brew install boost

      - name: Configure with CMake
        run: |
          cmake . -DPATCH_VERSION=${{ github.run_number }}

      - name: Build the project
        run: |
          cmake --build .

      - name: Run tests
        run: |
          cmake --build . --target test

      # Вывод содержимого директории resources для проверки наличия Info.plist
      - name: List files in resources directory
        run: ls -la ./resources  # Выводит список файлов в директории resources

      - name: Create package
        run: |
          cmake --build . --target package

      # Создание релиза и загрузка активов (остальные шаги остаются без изменений)
